### ISSUE TITLE
Problems running data explorer

### ISSUE THREAD

**Issue by johnburgato** [jfbouzereau/explorer#1]
I have come across your data explorer while looking for a good resource to visualize treemaps. It looks perfect. I am however finding it impossible to get the software to work. There may be a missing dependency that would be good to document on the install guide. I have node installed, but 

I am using v1.72 (Explorer-win32-x64.zip or Explorer-win32-ia32.zip or darwin) on Win 10.

If I try try to use Explorer.exe, when I drop a data file or "use clipboard" I receive a Javascrip error:

> EPERM: operation not permitted, write at Concole.log(console.js:36:16)
> at process_tabular_content (main.js:401:9)

If I try to open "resources/app/index.html" in Chrome or IE Edge, I can paste in my data, but then receive a large number of dialog alerts saying:

> draw error ReferenceError: process is not defined

**Comment by jfbouzereau** [comment]
On 03/11/15 17:53, "John B" notifications@github.com wrote:

> I have come across your data explorer while looking for a good resource
> to visualize treemaps. It looks perfect. I am however finding it
> impossible to get the software to work. There may be a missing dependency
> that would be good to document on the install guide. I have node
> installed, but 
> I am using v1.72 (Explorer-win32-x64.zip or Explorer-win32-ia32.zip or
> darwin) on Win 10.
> If I try try to use Explorer.exe, when I drop a data file or "use
> clipboard" I receive a Javascrip error:
> 
> EPERM: operation not permitted, write at Concole.log(console.js:36:16)
> at process_tabular_content (main.js:401:9)
> 
> If I try to open "resources/app/index.html" in Chrome or IE Edge, I can
> paste in my data, but then receive a large number of dialog alerts saying:
> 
> draw error ReferenceError: process is not defined
> 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/jfbouzereau/explorer/issues/1.

Hello,

Thanks for your message about the Explorer. Please
try to uncompress the attached zip file and copy
the resulting "app" folder into explorer/resources.
Let me know if this modified version solves your
problem. I will include it in the next release.

Best regards

JFB

---

Jean-François BOUZEREAU

## jfbouzereau@netcourrier.com

**Comment by johnburgato** [comment]
Thank you Jean-François... The new version seems to solve the problem when I run in the browser (thought it doesn't seem to pick up the "quantitative" fields, this may be a function of the clipboard as dragging & dropping Excel is fine), but there is still the same error when I run Explorer.exe

However, I did some experimenting myself and installed Electron with the Node Package Manager. I could then run electron against the project and it seems to work correctly. From reading around, I think the problem may be that the console some how does not exist when you run the application as the packaged executable, but is present when I execute electron/project from the command line.

**Comment by jfbouzereau** [comment]
Indeed , there seems to be a problem with the console on windows.  Running the program from the command prompt is ok, but launching it as a GUI process by double clicking on explorer.exe crashes with   EPERM error. The version 1.74 fixes this, by testing if the console work and disabling it if it does not.

**Comment by johnburgato** [comment]
Excellent, I'm happy to confirm that the latest version works when running the explorer.exe directly.
