### ISSUE TITLE
really want to use this program but ...

### ISSUE THREAD

**Issue by abozoki** [jfbouzereau/explorer#2]
It needs something like a user's manual!  The video is great, but doesn't cover the beginning.
There is no "start here," no indication of which file to start with to launch the program, nor how to trouble-shoot anything (e.g., I couldn't get it to read an Excel file directly, only by converting it to a .csv; it doesn't read in all the variables, only the first 10; it designates all of my variables as categorical even though some of them are clearly continuous), nor what the different icons do, other than their name when I mouse over them.
This program is really exciting because I've been looking for EXACTLY THIS- something to "look" at and explore my data in a straightforward way without endless layers of query boxes and scrolling through output files. Can you write just a little bit about how to get started?

**Comment by jfbouzereau** [comment]
On 20/12/15 22:20, "abozoki" notifications@github.com wrote:

> It needs something like a user's manual!  The video is great, but doesn't
> cover the beginning
> There is no "start here," no indication of which file to start with to
> launch the program, nor how to trouble-shoot anything (eg, I couldn't get
> it to read an Excel file directly, only by converting it to a csv; it
> doesn't read in all the variables, only the first 10; it designates all
> of my variables as categorical even though some of them are clearly
> continuous), nor what the different icons do, other than their name when
> I mouse over them
> This program is really exciting because I've been looking for EXACTLY
> THIS- something to "look" at and explore my data in a straightforward way
> without endless layers of query boxes and scrolling through output files
> Can you write just a little bit about how to get started?
> �
> Reply to this email directly or view it on GitHub
> https://github.com/jfbouzereau/explorer/issues/2.

Hello,

Thanks for your mail about the Explorer.

I know that the manual is missing. Writing documentation is always painful
to me,
and I tend to postpone it as much as possible :-(
I guess I will take advantage of the holidays to start something.

The Explorer should read Excel 2007+ files (that is with extension xlsx).
It doesn't read old files (with extension xls) . If some fields are not
recognized as numeric, maybe they have missing values , or the decimal
separator is not comma or dot . If your data are not confidential, you
may send me a sample file (my mail address is at the bottom of the
documentation)
I will check if something is wrong in the program.

The Explorer read all the fields, but by default displays only the first
10.
You can resize the list by moving the mouse just under the list, and drag.
Likewise, you can scroll the list by moving the mouse at the right of the
list.

I hope this will help a little , and allow you to start using it.

Cheers

JFB

**Comment by abozoki** [comment]
I may simply not be using the program correctly. Which page should I be using to launch the program?
When I click on “explorer.html” or “window.html” nothing happens.
When I click on “reader.html” I get a window with “drop file here” or use clipboard. When I drop the .xlsx or .csv it downloads it to the browser’s (Chrome) downloads directory but nothing launches. When I click on “index.html” I get a dialog box that says “paste data here.” That is the one I used, and copied and pasted the .csv file into it. When I did that, the program interface opened in the window, but all the variables are pink, despite some being formatted as “numbers” in both the .xlsx and .csv versions.

I’ve attached both the .xlsx version (which has more columns- it’s not as cleaned as the .csv version) and the .csv, in case you need to see them.

Thanks,
AB

**Comment by abozoki** [comment]
Thanks for clarifying everything. I really appreciate your prompt assistance.
