### ISSUE TITLE
version numbers broken on macOS

### ISSUE THREAD

**Issue by core-code** [jfbouzereau/explorer#5]
i've downloaded Version '1.104' but when selecting it in the Finder and using 'Get Info' it claims to be Version '0.35.6'

the **CFBundleVersion** and **CFBundleShortVersionString** entries in your **Info.plist** file are wrong

**Comment by jfbouzereau** [comment]
Hello,
Thanks for the remark. I am currently not able to build a new version, but fortunately the error doesn't impact the operation.
